### PR TITLE
Remove ads

### PR DESCRIPTION
**Pull request by Stylix58**
We don't need ads in docs. Our documentation is not a commercial product thinked for make money but a big help for use our framework.
So, @Tronic247, please merge this pull request in order to make everyone more happy with the navigation experience in your framework's documentation.

### CODE REVIEW

**Comment by Tronic247** [comment]
noop :(

**Comment by Stylix58** [comment]
> noop :(

You can explain?

**Comment by Tronic247** [comment]
I created this to earn money :D if you have other solutions please explain.

**Comment by Stylix58** [comment]
I have found this: https://www.ethicalads.io.

**Comment by Tronic247** [comment]
@Stylix58 I know ed it before. I'm planning to use Carbon Ads after receiving my Adsense payment.

**Pull request closed without merging**
