### PR TITLE
remove search and fix some bugs

### PR DESCRIPTION
**Pull request by Stylix58**

### CODE REVIEW

**Comment by Tronic247** [comment]
@Stylix58 can you explain the changes ?

**Comment by Stylix58** [comment]
I have removed search (if you want to re-add it, please really don't use docsearch! use native mkdocs search feature instead).

I have also added check in templates for check when titles is need to be displayed.

**Comment by Tronic247** [comment]
@Stylix58 I **need** to use docsearch. It's easy to confiure.

**Comment by Tronic247** [comment]
@Stylix58 R U there ?

**Comment by Stylix58** [comment]
Yes

**Comment by Stylix58** [comment]
> @Stylix58 I **need** to use docsearch. It's easy to configure.

OK...

**Comment by Stylix58** [comment]
Ypou can merge now but please add docsearch youself, because I code on a other project now.

**Comment by Tronic247** [comment]
@Stylix58  Thank you for contributing this framework :D

**Comment by Stylix58** [comment]
You have closed, not MERGED. Please reopen and merge really!

**Pull request closed without merging**
